base_dir: "/data/datasets/aryan/x-view-15" # YT-VIS Train directory
datasets: ["mp3d"]
K: 1
db_path: ""
# ids: [0,100,200,300,400,500,600,700,800,900] 
object_location: True 
filter_images: False
save_pkl: True
split: False
split_size: 0.2
airloc_model_path: '../models/airloc_model.pth'
netvlad_model_path: '../models/netvlad_model.pth'
graph_model_path: '../Models_to_save/gcn_model.pth'
camera:
  fx: 960
  fy: 960
  cx: 960.5
  cy: 540.4
  width: 1920
  height: 1080
good_image:
  occlusion_ratio: 0.1
  min_objects: 5
model:
  airloc:
    graph_model: "gat" #gcn
    descriptor_dim: 8192
    hidden_dim: 4096
    nout: 2048
    points_encoder_dims: [2, 4, 8, 16]
    dropout: 0.5  #0.5
    alpha: 0.2
    nheads: 8  #8
    train:
      seqlen: 4
      batch_size: 16
      positive_margin: 1
      negative_margin: 0.2
      lambda_d: 1
      epochs: 10
      lr: 0.0001 #0.1 #0.0001
      checkpoint: 500
  netvlad:
    descriptor_dim: 256
    vlad_numc: 32
  gcn:
    descriptor_dim: 256
    points_encoder_dims: [2, 4, 8, 16]
    hidden_dim: 512
    dropout: 0
    alpha: 0.2
    nheads: 4
    nout: 2048