base_dir: '/home/aryan/Airloc_Public/data_collection/x-view/data'
datasets: [mp3d]
log_dir: './experiments/train_airloc' # Logging directory
method: airloc
airloc_save_path: '../models/airloc_geometry_model.pth'
netvlad_model_path: '../models/netvlad_model.pth'
# scenes: ['8WUmhLawc2A', 'i5noydFURQK', 'jh4fc5c5qoQ', 'mJXqzFtmKg4', 'qoiz87JEwZ2', 'wc2JMjhGNzB', 'WYY7iVyf5p8', 'X7HyMhZNoso', 'YFuZgdQ5vWj', 'yqstnuAEVhm', 'VzqfbhrpDEA']
scenes: ["RPmz2sHmrrY",  "S9hNv5qa7GM",  "ULsKaCPVFJR" ] 
airloc_model_path: ''
database:
  config_path: ./config/generate_reference.yaml
  db_raw_path: /home/aryan/Airloc_Public/data_collection/x-view 
  db_path: "/home/aryan/Airloc_Public/data_collection/database"
  K: 1
model:
  airloc:
    descriptor_dim: 256
    hidden_dim: 512
    nout: 1024
    graph_model: gat
    points_encoder_dims: [12, 32, 64, 128, 256]
    dropout: 0.5 #0.5
    alpha: 0.2
    nheads: 8 #8
    temporal_encoder_dim: 2048
    temporal_encoder_out_dim: 2048
    temporal_kernel_size: 1
    train:
      seqlen: 4
      batch_size: 16
      positive_margin: 1
      negative_margin: 0.2
      lambda_d: 1
      epochs: 35
      lr: 0.0001
      checkpoint: 2
  netvlad:
    descriptor_dim: 256
    vlad_numc: 32
